apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: idp-wednesdaymvp
  description: asd
  annotations:
    github.com/project-slug: darede-labs/idp-wednesdaymvp
spec:
  type: service
  lifecycle: experimental
  owner: group:default/asd
